my:
 name: Jack
 age: 133
 number: ${random.int[100,999]}
 uuid: ${random.uuid}
 max: ${random.int(10)} 
 value: ${random.value} 
 greeting: Hi,I'm ${my.name}


name: osdf
hello: GOood
logging: 
 level: 
   com: 
   controller: trace
#spring: 
# profiles: 
# active: prod

#management:
#  security:
#    enabled: false #关掉安全认证
#  port: 8888 #管理端口调整成8888
#  context-path: /abc #actuator的访问路径

#配置安全
#security:
#  user:
#    name: admin 
#    password: admin

#配置端点
endpoints:
  actuator:
    enabled: true
  shutdown: 
    enabled: true

server: 
  port: 8032

spring: 
  boot: 
    admin: 
      url: http://localhost:8000
  application:  
    admin: 
      name: spring-boot-admin-client
management: 
  security: 
    enabled: false
